---
title: "ldp classifier"
author: "Flora Zhang and Dan Yurovsky"
date: "2/21/2019"
output: html_document
---

```{r}
library(tidyverse)
library(lme4)
library(here)
library(boot)
library(broom)
library(naivebayes)
library(irr)
library(tidyboot)
```

```{r old_data}
child_data <- read_tsv(here("data/ldp_child.csv")) %>%
  mutate(person = "child") %>%
  select(-X1)

parent_data <- read_tsv(here("data/ldp_parent.csv")) %>%
  mutate(person = "parent") %>%
  select(-X1)


all_data <- bind_rows(child_data, parent_data) %>%
  select(-id) %>%
  filter(!is.na(cnt_3S)) %>%
  mutate(person = as.numeric(factor(person, levels = c("parent", "child"))) - 1) 


train_data <- all_data %>%
  ungroup() %>%
  sample_frac(.8)

# not right
test_data <- anti_join(train_data, all_data)

test_data <- all_data %>%
  ungroup() %>%
  sample_frac(.2)

model <- glm(person ~ ., family = "binomial",data = train_data)

predicted_data <- test_data %>% 
  mutate(prediction = inv.logit(predict(model, newdata = .))) %>%
  mutate(is_child = prediction > .5)

```


```{r}

model <- glm(person ~ ., family = "binomial",data = all_data)


features <- tidy(model)

features %>%
  arrange(desc(abs(statistic)))

predicted_data <- all_data %>% 
  mutate(prediction = inv.logit(predict(model))) %>%
  mutate(is_child = prediction > .5)

cor.test(predicted_data$prediction, predicted_data$person)
```


```{r}
all_data %>%
  group_by(person) %>%
  summarise(bool_question = mean(bool_question, na.rm = T),
            cnt_MentalStateVerb = mean(cnt_MentalStateVerb))
```


```{r}
acc_data <- predicted_data %>%
  group_by(person, is_child) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  mutate(person = if_else(person == 0, "parent", "child"),
         predicted_person = if_else(is_child, "child", "parent"))


tp <-  acc_data %>%
  filter(person == "child" & predicted_person == "child") %>%
  summarise(n = sum(n)) %>%
  pull(n)

fp <- acc_data %>%
  filter(person == "parent", predicted_person == "child") %>%
  summarise(n = sum(n)) %>%
  pull(n)

fn <- acc_data %>%
  filter(person == "child", predicted_person == "parent") %>%
  summarise(n = sum(n)) %>%
  pull(n)


precision <- tp / (tp + fp)
recall <- tp / (tp + fn)

f <- (2 * (precision * recall)) / (precision + recall)
```


```{r new_data}
all_data <- read_tsv(here("data/02122019processed_alldata_with_identity_session_col.csv")) %>%
  select(-X, -id, -chat:-syntype, -identity_session)

tidy_data <- all_data %>%
  mutate(identity_binary = as.logical(identity_binary)) %>%
  select(-subject) %>%
  group_by(session)

nbs <- tidy_data %>%
  nest() %>%
  mutate(nb = map(data, ~naive_bayes(identity_binary ~ ., data = .x))) 

predicted <- nbs %>%
  mutate(predicted = map(nb, predict)) %>%
  select(-nb) %>%
  unnest()
```

```{r}
get_scores <- function(this_session, identity) {
    
  tp <- counts %>%
    filter(session == this_session & identity_binary == identity & 
             predicted == identity) %>%
    pull(n)
  
  fp <- counts %>%
    filter(session == this_session & identity_binary != identity & 
             predicted == identity) %>%
    pull(n)
  
  tn <- counts %>%
    filter(session == this_session & identity_binary != identity & 
             predicted != identity) %>%
    pull(n)
  
  fn <- counts %>%
    filter(session == this_session & identity_binary == identity & 
             predicted != identity) %>%
    pull(n)
  
  data_frame(session = this_session, identity_binary = identity, tp = tp, fp = fp,
             tn = tn, fn = fn)
}

counts <- predicted %>%
  group_by(session, identity_binary, predicted) %>%
  summarise(n = n()) %>%
  mutate(predicted = as.logical(predicted))


predicted %>%
  group_by(session, identity_binary) %>%
  summarise(n = n()) %>%
  mutate(predicted = as.logical(predicted))

ids <- counts %>%
  select(session, identity_binary) %>%
  distinct()

scores <- map2_dfr(ids$session, ids$identity_binary, get_scores) %>%
  mutate(precision = tp / (tp + tn),
         recall = tp / (tp + fn),
         f = (2 * precision * recall) / (precision + recall),
         accuracy = (tp + tn)/(tp + tn + fp + fn)) %>%
  mutate(identity_binary = factor(identity_binary, labels = c("child", "parent")))

scores %>%
  gather(measure, value, precision, recall, f, accuracy) %>%
  ggplot(aes(x = session, y = value, color = measure, group = measure)) + 
  facet_wrap(~identity_binary) + 
  geom_line() +
  theme_classic(base_size = 14)
ggsave("classifer.pdf")
```


```{r}
predicted_prob<- nbs %>%
  mutate(predicted = map(nb, ~predict(.x, type = "prob"))) %>%
  select(-nb) %>%
  mutate(predicted = map(predicted, as_tibble)) %>%
  unnest() %>%
  mutate(child = `TRUE`/(`FALSE` +`TRUE`))

cors <- predicted_prob %>%
  group_by(session) %>%
  summarise(cor = cor(child, identity_binary))

ggplot(cors, aes(x = session, y = cor)) + 
  geom_line() + 
  scale_x_continuous(breaks = 1:12) +
  scale_y_continuous(limits = c(0, .5)) +
  theme_classic(base_size = 14) 
ggsave("correlation.pdf")

```


```{r}
cor(all_data_predicted$identity_binary, all_data_predicted$predicted)

kappa2(all_data_predicted[c("identity_binary", "predicted")])
```